on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: [latest]
        os: [self-hosted, windows-latest]
    name: Haskell GHC ${{ matrix.ghc }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'
      - name: Testing helloworld
        run: stack test
      - name: Build helloworld
        run: stack build
      - name: Exec helloworld
        run: stack exec helloworld-exe